server {
    listen 80;
    listen [::]:80;
    server_name hongkongxiao2.ilelezhan.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name hongkongxiao2.ilelezhan.cn;

    ssl_certificate /etc/letsencrypt/live/hongkongxiao2.ilelezhan.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hongkongxiao2.ilelezhan.cn/privkey.pem;

    location ^~ /smartlife-primary-hk2-ws {
        proxy_pass http://127.0.0.1:19366;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 75s;
        proxy_send_timeout 75s;
    }

    location / {
        proxy_pass http://127.0.0.1:19367;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header Cache-Control "no-cache" always;
    }
}
