listener 19383 127.0.0.1
allow_anonymous true

persistence true
persistence_location /home/ubuntu/smartlife-primary-hk2/data/mosquitto/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
